### PR TITLE
Graphene Updates

### PR DESCRIPTION
**Pull request by nathanielhourt**
This adds the most important updates to Graphene from BitShares. It *shouldn't* affect consensus at all; if anything does, it's a bug and should be fixed back to normal Peerplays consensus.

This builds and runs; I'm not certain that it is correct.

## NOTE:
This uses a branch from my FC fork for FC. That's because my FC fork is not based on peerplays-fc, it's based on bitshares-fc. To accept this PReq, one should first make a new branch on peerplays-fc which is a copy of https://github.com/nathanhourt/peerplays-fc/tree/bts-updates and then update the submodule here.

### CODE REVIEW

**Comment by nathanhourt** [comment]
Oops, I had forgotten a few fixes in my working tree. Those are added and pushed now.

**Comment by bobinson** [comment]
For this PR to be considered the following is required:

-  list of the changes
- why each one is needed : ideally link to the Bitshares / Graphene / FC issues/PRs
- detailed test plan.

**Comment by nathanhourt** [comment]
Sure, no problem :)

Far and away the biggest and most important change here is [BTS #1506](https://github.com/bitshares/bitshares-core/issues/1506) which is an architectural refactor that moves the `chain/protocol` folder into its own library, thus enforcing the implied rule that code in the `protocol` may not reference code in `chain`.

The second major change here is the upgrade of FC from Peerplays' somewhat outdated fork to BitShares' fork, which is much more up-to-date, including an updating websocketpp to version 0.7.0. There are several changes in here to remove usage of deprecated functionality and to update Peerplays to use the new FC and dependencies.

Deprecated FC features which have been removed include:
 - Replace `fc::uint128` with boost equivalent ([BTS #1660](https://github.com/bitshares/bitshares-core/issues/1660))
 - Replace `fc::smart_ref` with `std::shared_ptr` ([BTS #1548](https://github.com/bitshares/bitshares-core/issues/1548))
 - Remove deprecated references to NTP (Peerplays wasn't using it anymore either, but it was still linked in)
 - Replace `fc::array` with `std::array` (No related issue; done to reduce maintenance burden)

Other changes included in this patch:
 - Several of Peter's updates to FC macros, to improve performance
 - Peter's fixes to endianness of serialization, to fix network compatibility with big endian systems
 - Remove `static_variant`'s deceptive `operator<` overload which compared types, but not values
 - Remove refs to `boost::signals` from the CMake project files, as it's header-only and no longer recognized by CMake
 - Update `extension` serialization ([BTS #723](https://github.com/bitshares/bitshares-core/pull/723))
 - Fix crash in `cli_wallet` ([BTS #1772](https://github.com/bitshares/bitshares-core/issues/1772))
 - A host of minor build fixes, test and crash fixes, warning fixes, and unused code removals
 - Rename the CMake project from `BitShares` to `Peerplays`, because this is Peerplays =)

As to testing, this patch is all refactors, bug/crash fixes, and updates to remain compatible with updated dependencies. It does not include any functional changes. Furthermore, excepting some very minor changes I made to Peerplays to fix the build, some crashes, and remove unused code, none of these changes are new; they've already been in use on BitShares for many months. As a result, minimal testing is necessary: ensure that all unit tests which are expected to pass continue to pass, and ensure that the code still synchronizes with Peerplays main chain and any testing chains. Any incompatibilities or regressions should be fixed. No further testing should be necessary.

Finally, before merging this to Peerplays, a new branch should be pushed to `peerplays-fc` which is a copy of [my FC branch](https://github.com/nathanhourt/peerplays-fc/tree/bts-updates), and the submodule in this PReq should be reverted back to `peerplays-fc` rather than my fork. I can update the PReq myself if an appropriate branch is added to `peerplays-fc`.

**Comment by bobinson** [comment]
So 5 issues / PRs in Bitshares to be referred for this PR ? 



> Peter's updates to FC macros,

A list of issues or PRs if any will be helpful.


> none of these changes are new; they've already been in use on BitShares for many months. As a result, minimal testing is necessary:

Can you provide more details as to how the QA is done on Bitshares and expected QA on this ?  (Testplans, sanity test cases etc will be of help to the PBSA QA team.)

**Comment by nathanhourt** [comment]
I was able to find these other pull requests that commits included here entered Bitshares from:
 - Peter's macro updates in [BTS #1768](https://github.com/bitshares/bitshares-core/pull/1768)
 - Endianness fixes in [BTS #1714](https://github.com/bitshares/bitshares-core/pull/1714)
 - static_variant operator overloads, and also the "Remove unused macro" commit above are covered in [BTS #1968](https://github.com/bitshares/bitshares-core/pull/1968)

Additional commits exist in the first two which are not included in this PReq. It may be advisable to add them to this PReq, as they will likely further accelerate the build and resolve other endianness issues. If you like, I can add them.

QA in BitShares was typically done by code review on pull requests by members of the core dev team. All pull requests were also required to pass automated build-and-test checks via Travis-CI. All functionality changes were expected to have several unit tests providing at least basic functionality verification, and when processing the code for release, of course it was tested to sync with the main and test nets.

Once again, since there are no functionality changes here, the expected QA process would be to verify that all tests that were passing before still pass and that the node still synchronizes with the chain. Ideally, the database would also be dumped from a node built with this patch and without this patch synchronized to the same block height on all supported chains, and those dumps compared to ensure that they are identical. If they are, then this patch should be considered correct.

**Comment by bobinson** [comment]
Thanks.

https://github.com/peerplays-network/peerplays/pull/137  addresses https://github.com/bitshares/bitshares-core/pull/1768

Will revert on the rest. Some of the changes might be already brought in so, its going to be tough task merging this PR.

**Comment by nathanhourt** [comment]
Oh, huh, that's weird. I only brought over commits I needed to make the main two changes I described (protocol separation and FC update) work.

I mentioned BTS #1768 because it contains two commits I brought in:
 - Separate exception declaration and implementation
 - Externalized serialization in protocol library

Of those two commits, I see that the "Externalized serialization" one is making rather minor changes here as most of its changes were already applied... So yeah, that's relatively insignificant and can probably be ignored.

The other one, "Separate exception declaration and implementation", was part of BTS #1768; however, it is *not* included in Peerplays #137 

So it appears that #137 was missing a few parts of #1768 that I needed, and so I added them in here.

**Pull request closed without merging**
