### PR TITLE
Update the FC submodule with the changes for GRPH-4

### PR DESCRIPTION
**Pull request by Noughmad**
* updates the check-out commit for the `fc` submodule
* updates a single test file to the new API so that tests build successfully

### CODE REVIEW

**Comment by Noughmad** [comment]
Fixes issue #119

**Comment by oxarbitrage** [comment]
trying, thanks.

**Comment by oxarbitrage** [comment]
Failing for me:

```
[ 83%] Building CXX object tests/CMakeFiles/cli_test.dir/cli/main.cpp.o
[ 84%] Linking CXX executable cli_test
CMakeFiles/cli_test.dir/cli/main.cpp.o: In function `graphene::db::abstract_object<graphene::chain::global_property_object>::move_from(graphene::db::object&)':
/home/oxarbitrage/CLionProjects/pp_pull121/peerplays/libraries/chain/include/graphene/chain/protocol/chain_parameters.hpp:45: undefined reference to `fc::smart_ref<graphene::chain::fee_schedule>::smart_ref(fc::smart_ref<graphene::chain::fee_schedule>&&)'
CMakeFiles/cli_test.dir/cli/main.cpp.o: In function `fc::impl::storage_ops<29, graphene::chain::committee_member_create_operation, graphene::chain::committee_member_update_operation, graphene::chain::committee_member_update_global_parameters_operation, graphene::chain::vesting_balance_create_operation, graphene::chain::vesting_balance_withdraw_operation, graphene::chain::worker_create_operation, graphene::chain::custom_operation, graphene::chain::assert_operation, graphene::chain::balance_claim_operation, graphene::chain::override_transfer_operation, graphene::chain::transfer_to_blind_operation, graphene::chain::blind_transfer_operation, graphene::chain::transfer_from_blind_operation, graphene::chain::asset_settle_cancel_operation, graphene::chain::asset_claim_fees_operation, graphene::chain::fba_distribute_operation, graphene::chain::tournament_create_operation, graphene::chain::tournament_join_operation, graphene::chain::game_move_operation, graphene::chain::asset_update_dividend_operation, graphene::chain::asset_dividend_distribution_operation, graphene::chain::tournament_payout_operation, graphene::chain::tournament_leave_operation, graphene::chain::sport_create_operation, graphene::chain::sport_update_operation, graphene::chain::event_group_create_operation, graphene::chain::event_group_update_operation, graphene::chain::event_create_operation, graphene::chain::event_update_operation, graphene::chain::betting_market_rules_create_operation, graphene::chain::betting_market_rules_update_operation, graphene::chain::betting_market_group_create_operation, graphene::chain::betting_market_create_operation, graphene::chain::bet_place_operation, graphene::chain::betting_market_group_resolve_operation, graphene::chain::betting_market_group_resolved_operation, graphene::chain::bet_adjusted_operation, graphene::chain::betting_market_group_cancel_unmatched_bets_operation, graphene::chain::bet_matched_operation, graphene::chain::bet_cancel_operation, graphene::chain::bet_canceled_operation, graphene::chain::betting_market_group_update_operation, graphene::chain::betting_market_update_operation, graphene::chain::event_update_status_operation, graphene::chain::sport_delete_operation, graphene::chain::event_group_delete_operation, graphene::chain::affiliate_payout_operation, graphene::chain::affiliate_referral_payout_operation, graphene::chain::lottery_asset_create_operation, graphene::chain::ticket_purchase_operation, graphene::chain::lottery_reward_operation, graphene::chain::lottery_end_operation, graphene::chain::sweeps_vesting_claim_operation>::con(int, void*)':
/home/oxarbitrage/CLionProjects/pp_pull121/peerplays/libraries/chain/include/graphene/chain/protocol/chain_parameters.hpp:45: undefined reference to `fc::smart_ref<graphene::chain::fee_schedule>::smart_ref()'
CMakeFiles/cli_test.dir/cli/main.cpp.o: In function `fc::impl::move_construct<fc::static_variant<graphene::chain::transfer_operation, graphene::chain::limit_order_create_operation, graphene::chain::limit_order_cancel_operation, graphene::chain::call_order_update_operation, graphene::chain::fill_order_operation, graphene::chain::account_create_operation, graphene::chain::account_update_operation, graphene::chain::account_whitelist_operation, graphene::chain::account_upgrade_operation, graphene::chain::account_transfer_operation, graphene::chain::asset_create_operation, graphene::chain::asset_update_operation, graphene::chain::asset_update_bitasset_operation, graphene::chain::asset_update_feed_producers_operation, graphene::chain::asset_issue_operation, graphene::chain::asset_reserve_operation, graphene::chain::asset_fund_fee_pool_operation, graphene::chain::asset_settle_operation, graphene::chain::asset_global_settle_operation, graphene::chain::asset_publish_feed_operation, graphene::chain::witness_create_operation, graphene::chain::witness_update_operation, graphene::chain::proposal_create_operation, graphene::chain::proposal_update_operation, graphene::chain::proposal_delete_operation, graphene::chain::withdraw_permission_create_operation, graphene::chain::withdraw_permission_update_operation, graphene::chain::withdraw_permission_claim_operation, graphene::chain::withdraw_permission_delete_operation, graphene::chain::committee_member_create_operation, graphene::chain::committee_member_update_operation, graphene::chain::committee_member_update_global_parameters_operation, graphene::chain::vesting_balance_create_operation, graphene::chain::vesting_balance_withdraw_operation, graphene::chain::worker_create_operation, graphene::chain::custom_operation, graphene::chain::assert_operation, graphene::chain::balance_claim_operation, graphene::chain::override_transfer_operation, graphene::chain::transfer_to_blind_operation, graphene::chain::blind_transfer_operation, graphene::chain::transfer_from_blind_operation, graphene::chain::asset_settle_cancel_operation, graphene::chain::asset_claim_fees_operation, graphene::chain::fba_distribute_operation, graphene::chain::tournament_create_operation, graphene::chain::tournament_join_operation, graphene::chain::game_move_operation, graphene::chain::asset_update_dividend_operation, graphene::chain::asset_dividend_distribution_operation, graphene::chain::tournament_payout_operation, graphene::chain::tournament_leave_operation, graphene::chain::sport_create_operation, graphene::chain::sport_update_operation, graphene::chain::event_group_create_operation, graphene::chain::event_group_update_operation, graphene::chain::event_create_operation, graphene::chain::event_update_operation, graphene::chain::betting_market_rules_create_operation, graphene::chain::betting_market_rules_update_operation, graphene::chain::betting_market_group_create_operation, graphene::chain::betting_market_create_operation, graphene::chain::bet_place_operation, graphene::chain::betting_market_group_resolve_operation, graphene::chain::betting_market_group_resolved_operation, graphene::chain::bet_adjusted_operation, graphene::chain::betting_market_group_cancel_unmatched_bets_operation, graphene::chain::bet_matched_operation, graphene::chain::bet_cancel_operation, graphene::chain::bet_canceled_operation, graphene::chain::betting_market_group_update_operation, graphene::chain::betting_market_update_operation, graphene::chain::event_update_status_operation, graphene::chain::sport_delete_operation, graphene::chain::event_group_delete_operation, graphene::chain::affiliate_payout_operation, graphene::chain::affiliate_referral_payout_operation, graphene::chain::lottery_asset_create_operation, graphene::chain::ticket_purchase_operation, graphene::chain::lottery_reward_operation, graphene::chain::lottery_end_operation, graphene::chain::sweeps_vesting_claim_operation> >::result_type fc::impl::storage_ops<10, graphene::chain::asset_create_operation, graphene::chain::asset_update_operation, graphene::chain::asset_update_bitasset_operation, graphene::chain::asset_update_feed_producers_operation, graphene::chain::asset_issue_operation, graphene::chain::asset_reserve_operation, graphene::chain::asset_fund_fee_pool_operation, graphene::chain::asset_settle_operation, graphene::chain::asset_global_settle_operation, graphene::chain::asset_publish_feed_operation, graphene::chain::witness_create_operation, graphene::chain::witness_update_operation, graphene::chain::proposal_create_operation, graphene::chain::proposal_update_operation, graphene::chain::proposal_delete_operation, graphene::chain::withdraw_permission_create_operation, graphene::chain::withdraw_permission_update_operation, graphene::chain::withdraw_permission_claim_operation, graphene::chain::withdraw_permission_delete_operation, graphene::chain::committee_member_create_operation, graphene::chain::committee_member_update_operation, graphene::chain::committee_member_update_global_parameters_operation, graphene::chain::vesting_balance_create_operation, graphene::chain::vesting_balance_withdraw_operation, graphene::chain::worker_create_operation, graphene::chain::custom_operation, graphene::chain::assert_operation, graphene::chain::balance_claim_operation, graphene::chain::override_transfer_operation, graphene::chain::transfer_to_blind_operation, graphene::chain::blind_transfer_operation, graphene::chain::transfer_from_blind_operation, graphene::chain::asset_settle_cancel_operation, graphene::chain::asset_claim_fees_operation, graphene::chain::fba_distribute_operation, graphene::chain::tournament_create_operation, graphene::chain::tournament_join_operation, graphene::chain::game_move_operation, graphene::chain::asset_update_dividend_operation, graphene::chain::asset_dividend_distribution_operation, graphene::chain::tournament_payout_operation, graphene::chain::tournament_leave_operation, graphene::chain::sport_create_operation, graphene::chain::sport_update_operation, graphene::chain::event_group_create_operation, graphene::chain::event_group_update_operation, graphene::chain::event_create_operation, graphene::chain::event_update_operation, graphene::chain::betting_market_rules_create_operation, graphene::chain::betting_market_rules_update_operation, graphene::chain::betting_market_group_create_operation, graphene::chain::betting_market_create_operation, graphene::chain::bet_place_operation, graphene::chain::betting_market_group_resolve_operation, graphene::chain::betting_market_group_resolved_operation, graphene::chain::bet_adjusted_operation, graphene::chain::betting_market_group_cancel_unmatched_bets_operation, graphene::chain::bet_matched_operation, graphene::chain::bet_cancel_operation, graphene::chain::bet_canceled_operation, graphene::chain::betting_market_group_update_operation, graphene::chain::betting_market_update_operation, graphene::chain::event_update_status_operation, graphene::chain::sport_delete_operation, graphene::chain::event_group_delete_operation, graphene::chain::affiliate_payout_operation, graphene::chain::affiliate_referral_payout_operation, graphene::chain::lottery_asset_create_operation, graphene::chain::ticket_purchase_operation, graphene::chain::lottery_reward_operation, graphene::chain::lottery_end_operation, graphene::chain::sweeps_vesting_claim_operation>::apply<fc::impl::move_construct<fc::static_variant<graphene::chain::transfer_operation, graphene::chain::limit_order_create_operation, graphene::chain::limit_order_cancel_operation, graphene::chain::call_order_update_operation, graphene::chain::fill_order_operation, graphene::chain::account_create_operation, graphene::chain::account_update_operation, graphene::chain::account_whitelist_operation, graphene::chain::account_upgrade_operation, graphene::chain::account_transfer_operation, graphene::chain::asset_create_operation, graphene::chain::asset_update_operation, graphene::chain::asset_update_bitasset_operation, graphene::chain::asset_update_feed_producers_operation, graphene::chain::asset_issue_operation, graphene::chain::asset_reserve_operation, graphene::chain::asset_fund_fee_pool_operation, graphene::chain::asset_settle_operation, graphene::chain::asset_global_settle_operation, graphene::chain::asset_publish_feed_operation, graphene::chain::witness_create_operation, graphene::chain::witness_update_operation, graphene::chain::proposal_create_operation, graphene::chain::proposal_update_operation, graphene::chain::proposal_delete_operation, graphene::chain::withdraw_permission_create_operation, graphene::chain::withdraw_permission_update_operation, graphene::chain::withdraw_permission_claim_operation, graphene::chain::withdraw_permission_delete_operation, graphene::chain::committee_member_create_operation, graphene::chain::committee_member_update_operation, graphene::chain::committee_member_update_global_parameters_operation, graphene::chain::vesting_balance_create_operation, graphene::chain::vesting_balance_withdraw_operation, graphene::chain::worker_create_operation, graphene::chain::custom_operation, graphene::chain::assert_operation, graphene::chain::balance_claim_operation, graphene::chain::override_transfer_operation, graphene::chain::transfer_to_blind_operation, graphene::chain::blind_transfer_operation, graphene::chain::transfer_from_blind_operation, graphene::chain::asset_settle_cancel_operation, graphene::chain::asset_claim_fees_operation, graphene::chain::fba_distribute_operation, graphene::chain::tournament_create_operation, graphene::chain::tournament_join_operation, graphene::chain::game_move_operation, graphene::chain::asset_update_dividend_operation, graphene::chain::asset_dividend_distribution_operation, graphene::chain::tournament_payout_operation, graphene::chain::tournament_leave_operation, graphene::chain::sport_create_operation, graphene::chain::sport_update_operation, graphene::chain::event_group_create_operation, graphene::chain::event_group_update_operation, graphene::chain::event_create_operation, graphene::chain::event_update_operation, graphene::chain::betting_market_rules_create_operation, graphene::chain::betting_market_rules_update_operation, graphene::chain::betting_market_group_create_operation, graphene::chain::betting_market_create_operation, graphene::chain::bet_place_operation, graphene::chain::betting_market_group_resolve_operation, graphene::chain::betting_market_group_resolved_operation, graphene::chain::bet_adjusted_operation, graphene::chain::betting_market_group_cancel_unmatched_bets_operation, graphene::chain::bet_matched_operation, graphene::chain::bet_cancel_operation, graphene::chain::bet_canceled_operation, graphene::chain::betting_market_group_update_operation, graphene::chain::betting_market_update_operation, graphene::chain::event_update_status_operation, graphene::chain::sport_delete_operation, graphene::chain::event_group_delete_operation, graphene::chain::affiliate_payout_operation, graphene::chain::affiliate_referral_payout_operation, graphene::chain::lottery_asset_create_operation, graphene::chain::ticket_purchase_operation, graphene::chain::lottery_reward_operation, graphene::chain::lottery_end_operation, graphene::chain::sweeps_vesting_claim_operation> > >(int, void*, fc::impl::move_construct<fc::static_variant<graphene::chain::transfer_operation, graphene::chain::limit_order_create_operation, graphene::chain::limit_order_cancel_operation, graphene::chain::call_order_update_operation, graphene::chain::fill_order_operation, graphene::chain::account_create_operation, graphene::chain::account_update_operation, graphene::chain::account_whitelist_operation, graphene::chain::account_upgrade_operation, graphene::chain::account_transfer_operation, graphene::chain::asset_create_operation, graphene::chain::asset_update_operation, graphene::chain::asset_update_bitasset_operation, graphene::chain::asset_update_feed_producers_operation, graphene::chain::asset_issue_operation, graphene::chain::asset_reserve_operation, graphene::chain::asset_fund_fee_pool_operation, graphene::chain::asset_settle_operation, graphene::chain::asset_global_settle_operation, graphene::chain::asset_publish_feed_operation, graphene::chain::witness_create_operation, graphene::chain::witness_update_operation, graphene::chain::proposal_create_operation, graphene::chain::proposal_update_operation, graphene::chain::proposal_delete_operation, graphene::chain::withdraw_permission_create_operation, graphene::chain::withdraw_permission_update_operation, graphene::chain::withdraw_permission_claim_operation, graphene::chain::withdraw_permission_delete_operation, graphene::chain::committee_member_create_operation, graphene::chain::committee_member_update_operation, graphene::chain::committee_member_update_global_parameters_operation, graphene::chain::vesting_balance_create_operation, graphene::chain::vesting_balance_withdraw_operation, graphene::chain::worker_create_operation, graphene::chain::custom_operation, graphene::chain::assert_operation, graphene::chain::balance_claim_operation, graphene::chain::override_transfer_operation, graphene::chain::transfer_to_blind_operation, graphene::chain::blind_transfer_operation, graphene::chain::transfer_from_blind_operation, graphene::chain::asset_settle_cancel_operation, graphene::chain::asset_claim_fees_operation, graphene::chain::fba_distribute_operation, graphene::chain::tournament_create_operation, graphene::chain::tournament_join_operation, graphene::chain::game_move_operation, graphene::chain::asset_update_dividend_operation, graphene::chain::asset_dividend_distribution_operation, graphene::chain::tournament_payout_operation, graphene::chain::tournament_leave_operation, graphene::chain::sport_create_operation, graphene::chain::sport_update_operation, graphene::chain::event_group_create_operation, graphene::chain::event_group_update_operation, graphene::chain::event_create_operation, graphene::chain::event_update_operation, graphene::chain::betting_market_rules_create_operation, graphene::chain::betting_market_rules_update_operation, graphene::chain::betting_market_group_create_operation, graphene::chain::betting_market_create_operation, graphene::chain::bet_place_operation, graphene::chain::betting_market_group_resolve_operation, graphene::chain::betting_market_group_resolved_operation, graphene::chain::bet_adjusted_operation, graphene::chain::betting_market_group_cancel_unmatched_bets_operation, graphene::chain::bet_matched_operation, graphene::chain::bet_cancel_operation, graphene::chain::bet_canceled_operation, graphene::chain::betting_market_group_update_operation, graphene::chain::betting_market_update_operation, graphene::chain::event_update_status_operation, graphene::chain::sport_delete_operation, graphene::chain::event_group_delete_operation, graphene::chain::affiliate_payout_operation, graphene::chain::affiliate_referral_payout_operation, graphene::chain::lottery_asset_create_operation, graphene::chain::ticket_purchase_operation, graphene::chain::lottery_reward_operation, graphene::chain::lottery_end_operation, graphene::chain::sweeps_vesting_claim_operation> > const&)':
/home/oxarbitrage/CLionProjects/pp_pull121/peerplays/libraries/chain/include/graphene/chain/protocol/chain_parameters.hpp:45: undefined reference to `fc::smart_ref<graphene::chain::fee_schedule>::smart_ref(fc::smart_ref<graphene::chain::fee_schedule>&&)'
CMakeFiles/cli_test.dir/cli/main.cpp.o: In function `fc::variant::variant<fc::smart_ref<graphene::chain::fee_schedule> >(fc::smart_ref<graphene::chain::fee_schedule> const&)':
/home/oxarbitrage/CLionProjects/pp_pull121/peerplays/libraries/fc/include/fc/variant.hpp:588: undefined reference to `fc::smart_ref<graphene::chain::fee_schedule>::operator*() const'
CMakeFiles/cli_test.dir/cli/main.cpp.o: In function `void fc::reflector<graphene::chain::chain_parameters>::visit<fc::from_variant_visitor<graphene::chain::chain_parameters> >(fc::from_variant_visitor<graphene::chain::chain_parameters> const&)':
/home/oxarbitrage/CLionProjects/pp_pull121/peerplays/libraries/fc/include/fc/variant.hpp:591: undefined reference to `fc::smart_ref<graphene::chain::fee_schedule>::operator*()'
CMakeFiles/cli_test.dir/cli/main.cpp.o: In function `void fc::from_variant<graphene::chain::chain_parameters>(fc::variant const&, fc::optional<graphene::chain::chain_parameters>&)':
/home/oxarbitrage/CLionProjects/pp_pull121/peerplays/libraries/chain/include/graphene/chain/protocol/chain_parameters.hpp:45: undefined reference to `fc::smart_ref<graphene::chain::fee_schedule>::smart_ref()'
/home/oxarbitrage/CLionProjects/pp_pull121/peerplays/libraries/chain/include/graphene/chain/protocol/chain_parameters.hpp:45: undefined reference to `fc::smart_ref<graphene::chain::fee_schedule>::smart_ref(fc::smart_ref<graphene::chain::fee_schedule>&&)'
CMakeFiles/cli_test.dir/cli/main.cpp.o: In function `std::_Function_handler<graphene::chain::global_property_object (), fc::api_connection::api_visitor::operator()<graphene::chain::global_property_object>(char const*, std::function<graphene::chain::global_property_object ()>&) const::{lambda()#1}>::_M_invoke(std::_Any_data const&)':
/home/oxarbitrage/CLionProjects/pp_pull121/peerplays/libraries/chain/include/graphene/chain/protocol/chain_parameters.hpp:45: undefined reference to `fc::smart_ref<graphene::chain::fee_schedule>::smart_ref()'
CMakeFiles/cli_test.dir/cli/main.cpp.o: In function `void fc::raw::pack<fc::datastream<unsigned long>, graphene::chain::fee_schedule>(fc::datastream<unsigned long>&, fc::smart_ref<graphene::chain::fee_schedule> const&)':
/home/oxarbitrage/CLionProjects/pp_pull121/peerplays/libraries/fc/include/fc/io/raw.hpp:212: undefined reference to `fc::smart_ref<graphene::chain::fee_schedule>::operator*() const'
CMakeFiles/cli_test.dir/cli/main.cpp.o: In function `void fc::reflector<graphene::chain::chain_parameters>::visit<fc::raw::detail::pack_object_visitor<fc::datastream<char*>, graphene::chain::chain_parameters> >(fc::raw::detail::pack_object_visitor<fc::datastream<char*>, graphene::chain::chain_parameters> const&)':
/home/oxarbitrage/CLionProjects/pp_pull121/peerplays/libraries/fc/include/fc/io/raw.hpp:212: undefined reference to `fc::smart_ref<graphene::chain::fee_schedule>::operator*() const'
collect2: error: ld returned 1 exit status
tests/CMakeFiles/cli_test.dir/build.make:140: recipe for target 'tests/cli_test' failed
make[2]: *** [tests/cli_test] Error 1
CMakeFiles/Makefile2:2701: recipe for target 'tests/CMakeFiles/cli_test.dir/all' failed
make[1]: *** [tests/CMakeFiles/cli_test.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by Noughmad** [comment]
@oxarbitrage Did you update the submodule before compiling? `git submodule update --init --recursive --force `

**Comment by oxarbitrage** [comment]
Yes i did that, still failing with the error i sent from here. Any other can give it a try ?

**Comment by Noughmad** [comment]
Did you try compiling in a new (empty) directory? 

Apart from that, it could be that you're linking against and old version of `fc`. If you have `fc` installed somewhere, it could be picking that up. Make sure it's linking against the version that you've just built.

**Comment by oxarbitrage** [comment]
hmm, here are the commands i am using for a clean installation:

```
git clone https://github.com/peerplays-network/peerplays
cd peerplays
git checkout -t origin/develop
git pull origin pull/121/head
git submodule update --init --recursive --force
BOOST_ROOT=$HOME/opt/boost_1_67_0
cmake -DBOOST_ROOT="$BOOST_ROOT" -DCMAKE_BUILD_TYPE=RelWithDebInfo .
make
```

**Comment by Noughmad** [comment]
Using the steps above I can finally this. Maybe it's the difference between compiling in-source and out-of-source, as I was doing before. I will try to fix this and update this PR.

**Comment by Noughmad** [comment]
@oxarbitrage I found the problem and fixed it, now it should compile successfully. Thank you for your help.

**Comment by bobinson** [comment]
@RoshanSyed  has made the CI available here : https://gitlab.com/PBSA/peerplays/pipelines

**Pull request merged**
