### PR TITLE
Enable mandatory plugins to have smooth transition for next release

### PR DESCRIPTION
**Pull request by pbattu123**
On bringing new elasticsearch plugin changes, witness should be able to run default plugins without plugin options. At the same time, witness should run other mandatory plugins like "witness" if only "elasticsearch" and "es-objects" passes under plugin options.
       Changes done to implement the above changes.
Note: we can't enable both account_history and elasticsearch plugins at the same time

### CODE REVIEW

**Comment by pbattu123** [comment]
https://peerplays.atlassian.net/browse/GRPH-176

**Comment by obucinac** [comment]
Please note that plugin handling, enable/disable and configuration is changed very much in incoming software versions. These two PRs are reflection of changes from Bitshares, and the way we are handling plugins in SONs-base branch.

https://github.com/peerplays-network/peerplays/pull/122
https://github.com/peerplays-network/peerplays/pull/126

With these two changes, enabling and disabling plugin is a single word in config file, and default set of plugins is hardcoded. With these, porting additional plugins from Bitshares will be much easier.

You should consider adding these PRs into develop branch.

**Comment by bobinson** [comment]
@pbattu123 - is `witness` plugin needed for seed nodes as well in the case of Peerplays ?

**Comment by pbattu123** [comment]
> @pbattu123 - is `witness` plugin needed for seed nodes as well in the case of Peerplays ?

No, it's not required

**Pull request merged**
