### PR TITLE
SON212-SON213 - Fix Build Error

### PR DESCRIPTION
**Pull request by satyakoneru**
Build Error

### CODE REVIEW

**Comment by oxarbitrage** [comment]
I am getting error in the linking of witness node now:

```
/home/oxarbitrage/CLionProjects/pp_pull262/peerplays/libraries/db/include/graphene/db/undo_database.hpp:69:22: note: in C++11 destructors default to noexcept
[ 80%] Linking CXX executable witness_node
../../libraries/plugins/peerplays_sidechain/libpeerplays_sidechain.a(peerplays_sidechain_plugin.cpp.o): In function `fc::impl::move_construct<fc::static_variant<graphene::chain::transfer_operation, graphene::chain::limit_order_create_operation, graphene::chain::limit_order_cancel_operation, graphene::chain::call_order_update_operation, graphene::chain::fill_order_operation, graphene::chain::account_create_operation, graphene::chain::account_update_operation, graphene::chain::account_whitelist_operation, graphene::chain::account_upgrade_operation, graphene::chain::account_transfer_operation, graphene::chain::asset_create_operation, graphene::chain::asset_update_operation, graphene::chain::asset_update_bitasset_operation, graphene::chain::asset_update_feed_producers_operation, graphene::chain::asset_issue_operation, graphene::chain::asset_reserve_operation, graphene::chain::asset_fund_fee_pool_operation, graphene::chain::asset_settle_operation, graphene::chain::asset_global_settle_operation, graphene::chain::asset_publish_feed_operation, graphene::chain::witness_create_operation, graphene::chain::witness_update_operation, graphene::chain::proposal_create_operation, graphene::chain::proposal_update_operation, graphene::chain::proposal_delete_operation, graphene::chain::withdraw_permission_create_operation, graphene::chain::withdraw_permission_update_operation, graphene::chain::withdraw_permission_claim_operation, graphene::chain::withdraw_permission_delete_operation, graphene::chain::committee_member_create_operation, graphene::chain::committee_member_update_operation, graphene::chain::committee_member_update_global_parameters_operation, graphene::chain::vesting_balance_create_operation, graphene::chain::vesting_balance_withdraw_operation, graphene::chain::worker_create_operation, graphene::chain::custom_operation, graphene::chain::assert_operation, graphene::chain::balance_claim_operation, graphene::chain::override_transfer_operation, graphene::chain::transfer_to_blind_operation, graphene::chain::blind_transfer_operation, graphene::chain::transfer_from_blind_operation, graphene::chain::asset_settle_cancel_operation, graphene::chain::asset_claim_fees_operation, graphene::chain::fba_distribute_operation, graphene::chain::tournament_create_operation, graphene::chain::tournament_join_operation, graphene::chain::game_move_operation, graphene::chain::asset_update_dividend_operation, graphene::chain::asset_dividend_distribution_operation, graphene::chain::tournament_payout_operation, graphene::chain::tournament_leave_operation, graphene::chain::sport_create_operation, graphene::chain::sport_update_operation, graphene::chain::event_group_create_operation, graphene::chain::event_group_update_operation, graphene::chain::event_create_operation, graphene::chain::event_update_operation, graphene::chain::betting_market_rules_create_operation, graphene::chain::betting_market_rules_update_operation, graphene::chain::betting_market_group_create_operation, graphene::chain::betting_market_create_operation, graphene::chain::bet_place_operation, graphene::chain::betting_market_group_resolve_operation, graphene::chain::betting_market_group_resolved_operation, graphene::chain::bet_adjusted_operation, graphene::chain::betting_market_group_cancel_unmatched_bets_operation, graphene::chain::bet_matched_operation, graphene::chain::bet_cancel_operation, graphene::chain::bet_canceled_operation, graphene::chain::betting_market_group_update_operation, graphene::chain::betting_market_update_operation, graphene::chain::event_update_status_operation, graphene::chain::sport_delete_operation, graphene::chain::event_group_delete_operation, graphene::chain::affiliate_payout_operation, graphene::chain::affiliate_referral_payout_operation, graphene::chain::lottery_asset_create_operation, graphene::chain::ticket_purchase_operation, graphene::chain::lottery_reward_operation, graphene::chain::lottery_end_operation, graphene::chain::sweeps_vesting_claim_operation, graphene::chain::son_create_operation, graphene::chain::son_update_operation, graphene::chain::son_delete_operation, graphene::chain::son_heartbeat_operation, graphene::chain::sidechain_address_add_operation, graphene::chain::sidechain_address_update_operation, graphene::chain::sidechain_address_delete_operation, graphene::chain::son_report_down_operation> >::result_type fc::impl::storage_ops<29, graphene::chain::committee_member_create_operation, graphene::chain::committee_member_update_operation, graphene::chain::committee_member_update_global_parameters_operation, graphene::chain::vesting_balance_create_operation, graphene::chain::vesting_balance_withdraw_operation, graphene::chain::worker_create_operation, graphene::chain::custom_operation, graphene::chain::assert_operation, graphene::chain::balance_claim_operation, graphene::chain::override_transfer_operation, graphene::chain::transfer_to_blind_operation, graphene::chain::blind_transfer_operation, graphene::chain::transfer_from_blind_operation, graphene::chain::asset_settle_cancel_operation, graphene::chain::asset_claim_fees_operation, graphene::chain::fba_distribute_operation, graphene::chain::tournament_create_operation, graphene::chain::tournament_join_operation, graphene::chain::game_move_operation, graphene::chain::asset_update_dividend_operation, graphene::chain::asset_dividend_distribution_operation, graphene::chain::tournament_payout_operation, graphene::chain::tournament_leave_operation, graphene::chain::sport_create_operation, graphene::chain::sport_update_operation, graphene::chain::event_group_create_operation, graphene::chain::event_group_update_operation, graphene::chain::event_create_operation, graphene::chain::event_update_operation, graphene::chain::betting_market_rules_create_operation, graphene::chain::betting_market_rules_update_operation, graphene::chain::betting_market_group_create_operation, graphene::chain::betting_market_create_operation, graphene::chain::bet_place_operation, graphene::chain::betting_market_group_resolve_operation, graphene::chain::betting_market_group_resolved_operation, graphene::chain::bet_adjusted_operation, graphene::chain::betting_market_group_cancel_unmatched_bets_operation, graphene::chain::bet_matched_operation, graphene::chain::bet_cancel_operation, graphene::chain::bet_canceled_operation, graphene::chain::betting_market_group_update_operation, graphene::chain::betting_market_update_operation, graphene::chain::event_update_status_operation, graphene::chain::sport_delete_operation, graphene::chain::event_group_delete_operation, graphene::chain::affiliate_payout_operation, graphene::chain::affiliate_referral_payout_operation, graphene::chain::lottery_asset_create_operation, graphene::chain::ticket_purchase_operation, graphene::chain::lottery_reward_operation, graphene::chain::lottery_end_operation, graphene::chain::sweeps_vesting_claim_operation, graphene::chain::son_create_operation, graphene::chain::son_update_operation, graphene::chain::son_delete_operation, graphene::chain::son_heartbeat_operation, graphene::chain::sidechain_address_add_operation, graphene::chain::sidechain_address_update_operation, graphene::chain::sidechain_address_delete_operation, graphene::chain::son_report_down_operation>::apply<fc::impl::move_construct<fc::static_variant<graphene::chain::transfer_operation, graphene::chain::limit_order_create_operation, graphene::chain::limit_order_cancel_operation, graphene::chain::call_order_update_operation, graphene::chain::fill_order_operation, graphene::chain::account_create_operation, graphene::chain::account_update_operation, graphene::chain::account_whitelist_operation, graphene::chain::account_upgrade_operation, graphene::chain::account_transfer_operation, graphene::chain::asset_create_operation, graphene::chain::asset_update_operation, graphene::chain::asset_update_bitasset_operation, graphene::chain::asset_update_feed_producers_operation, graphene::chain::asset_issue_operation, graphene::chain::asset_reserve_operation, graphene::chain::asset_fund_fee_pool_operation, graphene::chain::asset_settle_operation, graphene::chain::asset_global_settle_operation, graphene::chain::asset_publish_feed_operation, graphene::chain::witness_create_operation, graphene::chain::witness_update_operation, graphene::chain::proposal_create_operation, graphene::chain::proposal_update_operation, graphene::chain::proposal_delete_operation, graphene::chain::withdraw_permission_create_operation, graphene::chain::withdraw_permission_update_operation, graphene::chain::withdraw_permission_claim_operation, graphene::chain::withdraw_permission_delete_operation, graphene::chain::committee_member_create_operation, graphene::chain::committee_member_update_operation, graphene::chain::committee_member_update_global_parameters_operation, graphene::chain::vesting_balance_create_operation, graphene::chain::vesting_balance_withdraw_operation, graphene::chain::worker_create_operation, graphene::chain::custom_operation, graphene::chain::assert_operation, graphene::chain::balance_claim_operation, graphene::chain::override_transfer_operation, graphene::chain::transfer_to_blind_operation, graphene::chain::blind_transfer_operation, graphene::chain::transfer_from_blind_operation, graphene::chain::asset_settle_cancel_operation, graphene::chain::asset_claim_fees_operation, graphene::chain::fba_distribute_operation, graphene::chain::tournament_create_operation, graphene::chain::tournament_join_operation, graphene::chain::game_move_operation, graphene::chain::asset_update_dividend_operation, graphene::chain::asset_dividend_distribution_operation, graphene::chain::tournament_payout_operation, graphene::chain::tournament_leave_operation, graphene::chain::sport_create_operation, graphene::chain::sport_update_operation, graphene::chain::event_group_create_operation, graphene::chain::event_group_update_operation, graphene::chain::event_create_operation, graphene::chain::event_update_operation, graphene::chain::betting_market_rules_create_operation, graphene::chain::betting_market_rules_update_operation, graphene::chain::betting_market_group_create_operation, graphene::chain::betting_market_create_operation, graphene::chain::bet_place_operation, graphene::chain::betting_market_group_resolve_operation, graphene::chain::betting_market_group_resolved_operation, graphene::chain::bet_adjusted_operation, graphene::chain::betting_market_group_cancel_unmatched_bets_operation, graphene::chain::bet_matched_operation, graphene::chain::bet_cancel_operation, graphene::chain::bet_canceled_operation, graphene::chain::betting_market_group_update_operation, graphene::chain::betting_market_update_operation, graphene::chain::event_update_status_operation, graphene::chain::sport_delete_operation, graphene::chain::event_group_delete_operation, graphene::chain::affiliate_payout_operation, graphene::chain::affiliate_referral_payout_operation, graphene::chain::lottery_asset_create_operation, graphene::chain::ticket_purchase_operation, graphene::chain::lottery_reward_operation, graphene::chain::lottery_end_operation, graphene::chain::sweeps_vesting_claim_operation, graphene::chain::son_create_operation, graphene::chain::son_update_operation, graphene::chain::son_delete_operation, graphene::chain::son_heartbeat_operation, graphene::chain::sidechain_address_add_operation, graphene::chain::sidechain_address_update_operation, graphene::chain::sidechain_address_delete_operation, graphene::chain::son_report_down_operation> > >(int, void*, fc::impl::move_construct<fc::static_variant<graphene::chain::transfer_operation, graphene::chain::limit_order_create_operation, graphene::chain::limit_order_cancel_operation, graphene::chain::call_order_update_operation, graphene::chain::fill_order_operation, graphene::chain::account_create_operation, graphene::chain::account_update_operation, graphene::chain::account_whitelist_operation, graphene::chain::account_upgrade_operation, graphene::chain::account_transfer_operation, graphene::chain::asset_create_operation, graphene::chain::asset_update_operation, graphene::chain::asset_update_bitasset_operation, graphene::chain::asset_update_feed_producers_operation, graphene::chain::asset_issue_operation, graphene::chain::asset_reserve_operation, graphene::chain::asset_fund_fee_pool_operation, graphene::chain::asset_settle_operation, graphene::chain::asset_global_settle_operation, graphene::chain::asset_publish_feed_operation, graphene::chain::witness_create_operation, graphene::chain::witness_update_operation, graphene::chain::proposal_create_operation, graphene::chain::proposal_update_operation, graphene::chain::proposal_delete_operation, graphene::chain::withdraw_permission_create_operation, graphene::chain::withdraw_permission_update_operation, graphene::chain::withdraw_permission_claim_operation, graphene::chain::withdraw_permission_delete_operation, graphene::chain::committee_member_create_operation, graphene::chain::committee_member_update_operation, graphene::chain::committee_member_update_global_parameters_operation, graphene::chain::vesting_balance_create_operation, graphene::chain::vesting_balance_withdraw_operation, graphene::chain::worker_create_operation, graphene::chain::custom_operation, graphene::chain::assert_operation, graphene::chain::balance_claim_operation, graphene::chain::override_transfer_operation, graphene::chain::transfer_to_blind_operation, graphene::chain::blind_transfer_operation, graphene::chain::transfer_from_blind_operation, graphene::chain::asset_settle_cancel_operation, graphene::chain::asset_claim_fees_operation, graphene::chain::fba_distribute_operation, graphene::chain::tournament_create_operation, graphene::chain::tournament_join_operation, graphene::chain::game_move_operation, graphene::chain::asset_update_dividend_operation, graphene::chain::asset_dividend_distribution_operation, graphene::chain::tournament_payout_operation, graphene::chain::tournament_leave_operation, graphene::chain::sport_create_operation, graphene::chain::sport_update_operation, graphene::chain::event_group_create_operation, graphene::chain::event_group_update_operation, graphene::chain::event_create_operation, graphene::chain::event_update_operation, graphene::chain::betting_market_rules_create_operation, graphene::chain::betting_market_rules_update_operation, graphene::chain::betting_market_group_create_operation, graphene::chain::betting_market_create_operation, graphene::chain::bet_place_operation, graphene::chain::betting_market_group_resolve_operation, graphene::chain::betting_market_group_resolved_operation, graphene::chain::bet_adjusted_operation, graphene::chain::betting_market_group_cancel_unmatched_bets_operation, graphene::chain::bet_matched_operation, graphene::chain::bet_cancel_operation, graphene::chain::bet_canceled_operation, graphene::chain::betting_market_group_update_operation, graphene::chain::betting_market_update_operation, graphene::chain::event_update_status_operation, graphene::chain::sport_delete_operation, graphene::chain::event_group_delete_operation, graphene::chain::affiliate_payout_operation, graphene::chain::affiliate_referral_payout_operation, graphene::chain::lottery_asset_create_operation, graphene::chain::ticket_purchase_operation, graphene::chain::lottery_reward_operation, graphene::chain::lottery_end_operation, graphene::chain::sweeps_vesting_claim_operation, graphene::chain::son_create_operation, graphene::chain::son_update_operation, graphene::chain::son_delete_operation, graphene::chain::son_heartbeat_operation, graphene::chain::sidechain_address_add_operation, graphene::chain::sidechain_address_update_operation, graphene::chain::sidechain_address_delete_operation, graphene::chain::son_report_down_operation> > const&)':
/home/oxarbitrage/CLionProjects/pp_pull262/peerplays/libraries/chain/include/graphene/chain/protocol/chain_parameters.hpp:52: undefined reference to `fc::smart_ref<graphene::chain::fee_schedule>::smart_ref(fc::smart_ref<graphene::chain::fee_schedule>&&)'
collect2: error: ld returned 1 exit status
programs/witness_node/CMakeFiles/witness_node.dir/build.make:137: recipe for target 'programs/witness_node/witness_node' failed
make[2]: *** [programs/witness_node/witness_node] Error 1
CMakeFiles/Makefile2:2408: recipe for target 'programs/witness_node/CMakeFiles/witness_node.dir/all' failed
make[1]: *** [programs/witness_node/CMakeFiles/witness_node.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
oxarbitrage@oxarbitrage:~/CLionProjects/pp_pull262/peerplays$ 
```

**Comment by satyakoneru** [comment]
@oxarbitrage I've given a couple of clean builds till now and haven't been able to encounter any such error. Below are the steps followed. 

git clone https://github.com/peerplays-network/peerplays.git
cd peerplays/
git checkout remotes/origin/SON212_SON213_BuildError
git submodule update --init --recursive
cmake -DBOOST_ROOT="$BOOST_ROOT" -DCMAKE_BUILD_TYPE=Release
make -j$(nproc)

**Comment by oxarbitrage** [comment]
please try `-DCMAKE_BUILD_TYPE=RelWithDebInfo`

**Comment by bobinson** [comment]
manually triggered gitlab build

**Comment by bobinson** [comment]
merging as local build worked.

**Pull request merged**
