### PR TITLE
Reorder operations in Dockerfile, to make image creation faster

### PR DESCRIPTION
**Pull request by obucinac**

### CODE REVIEW

**Comment by obucinac** [comment]
After this merge, we can delete gcc 7 fix branch, I will not update it anymore.

**Comment by obucinac** [comment]
ntp is not needed, since docker image always syncs time with a host it is running on.

**Comment by bobinson** [comment]
> ntp is not needed, since docker image always syncs time with a host it is running on.

What if the host is not having NTP ? :)

**Comment by obucinac** [comment]
It appears there is a builtin NTP client:
https://github.com/peerplays-network/peerplays/blob/master/libraries/time/time.cpp

**Comment by obucinac** [comment]
Already merged

**Pull request closed without merging**
