### PR TITLE
[SON-110] get_son cli test

### PR DESCRIPTION
**Pull request by gladcow**
`get_son` cli API test

### CODE REVIEW

**Comment by pbsa-dev** [comment]
QA can look for "Cli get_son Test" in the CI logs.

**Comment by bobinson** [comment]
CI has 2 failures:

https://gitlab.com/PBSA/peerplays/-/jobs/317868374

` /home/gitlab-runner/builds/QDsbRVVn/0/PBSA/peerplays/tests/tests/son_operations_tests.cpp(131): fatal error: in "son_operation_tests/delete_son_test": critical check idx.empty() has failed
`

```

unknown location(0): fatal error: in "affiliate_tests/statistics_test": unknown type
/home/gitlab-runner/builds/QDsbRVVn/0/PBSA/peerplays/tests/tests/affiliate_tests.cpp(633): last checkpoint

```

**Comment by gladcow** [comment]
This test fails in `feature/SONs-base`. It is not functionality of this PR,  I'll create separate PR to fix the issue with `delete_son`

**Comment by pbsa-dev** [comment]
LGTM and merging as the tests are getting fixed elsewhere.

**Pull request merged**
