### PR TITLE
[GRPH 92] Build optimization

### PR DESCRIPTION
**Pull request by gladcow**
Backport of the https://github.com/bitshares/bitshares-core/pull/1768

> The idea is to explicitly specialize certain templates (mostly exceptions, APIs and serialization) in .cpp files and declare them extern in .hpp files. This avoids them being instantiated (and thus compiled) separately whereever they are used.

QA notes: this pull request doesn't change the code behavior, so all tests should pass as before.

### CODE REVIEW

**Comment by oxarbitrage** [comment]
Any upgrades on this one ? If applied correctly it is a great improvement in the build time.

**Comment by oxarbitrage** [comment]
Another good one that we could consider as optimization to do in the future is IMO https://github.com/bitshares/bitshares-core/pull/1737

**Comment by gladcow** [comment]
I need to update this PR to the actual `develop` state,  so now it is Work-In-Progress

**Comment by oxarbitrage** [comment]
Getting build error with the last version, please check:

https://github.com/oxarbitrage/logs/blob/master/peerplays_pull137_build.txt

**Comment by gladcow** [comment]
@oxarbitrage ,  I've fixed the issue, re-review, please

**Pull request merged**
