### PR TITLE
BLOCKBACK- 155: allow token holder to vote in each subperiod without unvote

### PR DESCRIPTION
**Pull request by pbattu123**
allow token holder to vote in each subperiod without unvote
Added more parameters for get_gpos_info api

### CODE REVIEW

**Comment by pbattu123** [comment]
Addressed all issues and updated `voting` unit test cases(also separated GPOS test suite to ease in running the test cases until finishing the development)

**Comment by oxarbitrage** [comment]
I think we should get back the tests into the `chain_test`. I don't see the benefit of separating them to later put them back again where they were.

Please note that you can run the specific gpos tests as:

`./tests/chain_test -t gpos_tests`

**Comment by pbattu123** [comment]
Deleted as per suggestion(it doesn't make any big difference).

**Comment by oxarbitrage** [comment]
`voting_tests` failing.

**Comment by pbattu123** [comment]
> `voting_tests` failing.

Please update hardkfork date to multiples of hours like Oct 24 1:00:00 with out minutes and seconds in your local branch and test.
Because GPOS tests completely depends on maintenance intervals.

**Pull request merged**
