### PR TITLE
WIP: Feature sidechain

### PR DESCRIPTION
**Pull request by pixelplex**
This WIP (work in progress) request only for comparing the changes

### CODE REVIEW

**Comment by xeroc** [comment]
Given the purpose of this code, can you please provide a specification and push it to
https://github.com/peerplays-network/pips

**Comment by xeroc** [comment]
Please note that consensus/protocol changing pull requests **require** a [PIP](https://github.com/peerplays-network/pips) to be written. An example of a PIP that (proposes to) change(s) consensus is provided [here](https://github.com/peerplays-network/pips/blob/master/pip-0002.md). More documents of similar share can be found for [BitShares](https://github.com/bitshares/bsips/), [Bitcoin](https://github.com/bitcoin/bips/) and [Ethereum](https://github.com/ethereum/EIPs).

Since code changes that affect the blockchain protocol require a hardfork, consensus from the witnesses is required which itself requires approval by the PPY token holders. The PIPs are to make it easier for **them** to judge and approve a protocol change.

That said, I assume this branch will not see any love from community developers until there are specifications in the form of a PIP that (at least) gives a technical overview of backend/protocol changes.

**Comment by viktor32** [comment]
ok, no problem. We will create it

**Comment by bobinson** [comment]
Bitcoin sidechain to be achieved by SONs

**Pull request closed without merging**
